// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwWu4BqUv98uCA3jpcQJjvcQMW7l0S0do',
    appId: '1:653906030361:web:8d90ab5977f2a9236f9f88',
    messagingSenderId: '653906030361',
    projectId: 'market-2c186',
    authDomain: 'market-2c186.firebaseapp.com',
    storageBucket: 'market-2c186.appspot.com',
    measurementId: 'G-Y82VTZ8C1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArbqbRni--Gbirho6lYyhzpYEphf3-Sxg',
    appId: '1:653906030361:android:28279b7c151da2486f9f88',
    messagingSenderId: '653906030361',
    projectId: 'market-2c186',
    storageBucket: 'market-2c186.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXsL-h5pc2L7RQpgdx1NrzLSAzQwEvMCM',
    appId: '1:653906030361:ios:9f2691380a8702886f9f88',
    messagingSenderId: '653906030361',
    projectId: 'market-2c186',
    storageBucket: 'market-2c186.appspot.com',
    iosBundleId: 'com.example.marketApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXsL-h5pc2L7RQpgdx1NrzLSAzQwEvMCM',
    appId: '1:653906030361:ios:9f2691380a8702886f9f88',
    messagingSenderId: '653906030361',
    projectId: 'market-2c186',
    storageBucket: 'market-2c186.appspot.com',
    iosBundleId: 'com.example.marketApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwWu4BqUv98uCA3jpcQJjvcQMW7l0S0do',
    appId: '1:653906030361:web:ba88c8ded6e6bbd96f9f88',
    messagingSenderId: '653906030361',
    projectId: 'market-2c186',
    authDomain: 'market-2c186.firebaseapp.com',
    storageBucket: 'market-2c186.appspot.com',
    measurementId: 'G-CEV5EWZWJ1',
  );
}
